base_name: dungeon


dungeon_area:
  size: # (height, width)
    - 80
    - 80

  fullness: 0.8

  room_size_method: fixed # fixed, range or factor
  fixed_room_size: # (height, width)
    - 10
    - 10
  range_room_size: # (min_height, max_height, min_width, max_width)
    - 10
    - 20
    - 10
    - 10
  factor_room_size: # (min_height, max_height, min_width, max_width)
    - 0.1
    - 0.3
    - 0.1
    - 0.3
